### ISSUE TITLE
Belépő oldal

### ISSUE THREAD

**Issue by pmhyi** [pmhyi/rft#10]
A már regisztrált felhasználó bejelentkezését biztosítani, avagy a még nem regisztráltnak regisztrációs lehetőség.

**Comment by mark403** [comment]
"<!-- Bejelentkező oldal kész: --!>

<!Docptye html>
<html>
	<head>
		<link rel="stylesheet" type="text/css" href="styles/loginstil.css">
		<meta charset="utf-8">
		<title>Üdvüzlönk a Snapface oldalon!</title>
	</head>
	<body>
		<?php

		?>
		<div id="header">
			<img style="float: left;" src="images/icon.png" width="200">
			<font class="titletext">Üdvözlünk a Snapface oldalon</font>
		</div>
		<div id="logger">
			<?php
				function goToReg() {
					header("Location: regiszt.php");
				}
				function logSnapIn(){
					header("Location: index.php");
				}
			?>
			<form action="index.php" method="post">
				<label>E-mail:</label><input type="text" name="email" id="email"><br>
				<label>Jelszó:  </label><input type="password" name="passwd" id="passwd"><center style="margin-top: 25px; padding: 5px;">
				<button type="submit" class="rlbutton" id="log" >Belépés</button>
				<button class="rlbutton" id="reg" >Regisztráció</button></center>
			</form>
		</div>
	</body>
</html>"

**Comment by mark403** [comment]
Belépés ellenőrzés:
"<?php
	session_start();
	if(!isset($_SESSION["belepett"])){
		header("Location: login.php");
	}
?> "
