### ISSUE TITLE
Események

### ISSUE THREAD

**Issue by benjitheweirdo** [pmhyi/rft#7]
Események hozzáadása, adatok felvitele az adatbázisba PHP-val

**Comment by mark403** [comment]
@pmhyi 
eventeket + a hozzáadásukat commitolni ameddig megvan

**Comment by pmhyi** [comment]
if(isset($_POST['submit'])){
	$con=mysql_connect('localhost', '1261234','RFTprojekt');
 
 if (!$con)
  {
  die('Could not connect: ' . mysql_error());
  }
mysql_select_db('1261234');			
 
$sql="INSERT INTO event (id, admin_id,name, start_time, duration, local, lead) VALUES ('', '$_POST[admin_id]', '$_POST[name]', '$_POST[start_time]', '$_POST[duration]', '$_POST[local]', '$_POST[lead]')";
mysql_query($sql, $con);
mysql_close($con);
	}

**Comment by pmhyi** [comment]
- [x] Saját  események kilistázása az adatlapon:
`<?php
	require_once("ifloggedin.php");
	require_once("adatok.php");
	$person = GetOwnData($_SESSION["userid"]);	
	require_once("ifloggedin.php");
	require_once("adatok.php");
	mysql_connect('localhost', 'root','');
	mysql_select_db('snapface');
	$sql="SELECT * FROM event WHERE admin_id=".$_SESSION["userid"];
	$records=mysql_query($sql);
 
?>`
`<h2` style="color:white">Eseményeim</h2>
				<?php
while($rows=mysql_fetch_assoc($records))
{
 $name=$rows['name'];
$start_time=$rows['start_time'];
$duration=$rows['duration'];
$local=$rows['local'];
$lead=$rows['lead'];
$leadpic=$rows['leadpic'];
 
echo "<article class=\"eventblock\"><table><tr><td><p>Esemény megnevezése:</td><td><p>".$name."</td></tr><tr><td><p>Dátum:</td><td><p>".$start_time." </td></tr><tr><td><p>Tartama:</td><td><p>".$duration."</td></tr><tr><td><p>Helye:</td><td><p>".$local."</td></tr><tr><td><p>Leírás:</td><td><p>".$lead."</td></tr><tr><td><p>".$leadpic."</p></td></tr></table></article>";
 
}
 
?>``
